import pycountry
from collections import defaultdict
from collections import OrderedDict

MAPPINGS = {
    # Africa
    "Democratic Republic of the Congo": 'Congo, The Democratic Republic of the',
    "Ivory Coast": "Côte d'Ivoire",
    "Tanzania": "Tanzania, United Republic of",
    "Iran": "Iran, Islamic Republic of",

    # Asia
    "Macau": "Macao",
    "Northern Cyprus": "Cyprus",
    "South Korea": "Korea, Republic of",
    "North Korea": "Korea, Democratic People's Republic of",
    "Vietnam": "Viet Nam",
    "Palestine": "Palestine, State of",
    "Taiwan": "Taiwan, Province of China",
    "Syria": "Syrian Arab Republic",

    # Europe
    "Macedonia": "Macedonia, Republic of",
    "Moldova": "Moldova, Republic of",
    "Russia": "Russian Federation",
    "Vatican City/Holy See": "Holy See (Vatican City State)",

    # North America
    "Bonaire": "Bonaire, Sint Eustatius and Saba",
    "British Virgin Islands": "Virgin Islands, British",
    "Saint Martin": "Saint Martin (French part)",
    "Sint Maarten": "Sint Maarten (Dutch part)",
    "United States of America": "United States",
    "United States Virgin Islands": "Virgin Islands, U.S.",

    # South America
    "Bolivia": "Bolivia, Plurinational State of",
    "Falkland Islands": "Falkland Islands (Malvinas)",
    "Venezuela": "Venezuela, Bolivarian Republic of",

    # Oceania
    "Pitcairn Islands": "Pitcairn",
    "Micronesia": "Micronesia, Federated States of",

    # Antartica
    "French Southern and Antarctic Lands": "French Southern Territories",
}

COUNTRIES = {
    "Africa": [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Réunion",
        "Rwanda",
        # "Sahrawi Arab Democratic Republic",
        "Saint Helena, Ascension and Tristan da Cunha",
        # "São Tomé and Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        # "Somaliland",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Swaziland",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ],
    "Asia": [
        "China",
        "Christmas Island",
        "Hong Kong",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        # "Laos",
        "Lebanon",
        "Macau",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Myanmar",
        # "Nagorno-Karabakh",
        "Nepal",
        "Northern Cyprus",
        "North Korea",
        "Oman",
        "Pakistan",
        "Palestine",
        "Philippines",
        "Qatar",
        "Saudi Arabia",
        "Singapore",
        "South Korea",
        # "South Ossetia",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Turkey",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen",
    ],
    "Europe": [
        "Åland Islands",
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Germany",
        "Gibraltar",
        "Greece",
        "Guernsey",
        "Hungary",
        "Iceland",
        "Ireland",
        "Isle of Man",
        "Italy",
        # "Jan Mayen",  # see Svalbard
        "Jersey",
        # "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        # "Svalbard",
        "Svalbard and Jan Mayen",
        "Sweden",
        "Switzerland",
        # "Transnistria",
        "Ukraine",
        "United Kingdom",
        "Vatican City/Holy See",
    ],
    "NorthAmerica": [
        "Anguilla",
        "Antigua and Barbuda",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bermuda",
        "Bonaire",
        "British Virgin Islands",
        "Canada",
        "Cayman Islands",
        # "Clipperton Island",
        "Costa Rica",
        "Cuba",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "El Salvador",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Martinique",
        "Mexico",
        "Montserrat",
        # "Navassa Island",
        "Nicaragua",
        "Panama",
        "Puerto Rico",
        # "Saba",
        "Saint Barthélemy",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        # "Sint Eustatius",
        "Sint Maarten",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "United States of America",
        "United States Virgin Islands",
    ],
    "SouthAmerica": [
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Falkland Islands",
        "French Guiana",
        "Guyana",
        "Paraguay",
        "Peru",
        "South Georgia and the South Sandwich Islands",
        "Suriname",
        "Uruguay",
        "Venezuela",
    ],
    "Oceania": [
        "American Samoa",
        # "Ashmore and Cartier Islands",
        "Australia",
        # "Baker Island",
        "Cook Islands",
        # "Coral Sea Islands",
        "Fiji",
        "French Polynesia",
        "Guam",
        # "Howland Island",
        # "Jarvis Island",
        # "Johnston Atoll",
        # "Kingman Reef",
        "Kiribati",
        "Marshall Islands",
        "Micronesia",
        # "Midway Atoll",
        "Nauru",
        "New Caledonia",
        "New Zealand",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Palau",
        # "Palmyra Atoll",
        "Papua New Guinea",
        "Pitcairn Islands",
        "Samoa",
        "Solomon Islands",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
        # "Wake Island",
        "Wallis and Futuna",
    ],
    "Antartica": [
        "Bouvet Island",
        "French Southern and Antarctic Lands",
        "Heard Island and McDonald Islands",
        "South Georgia and the South Sandwich Islands",
    ],
}

def _order_countries_dict(countries):
    return OrderedDict(sorted(countries.items(), key=lambda x: x[1]["name"]))

def get_countries_dict():
    result = defaultdict(dict)
    alpha_map = {c.name: c.alpha3 for c in pycountry.countries}
    for continent, countries in COUNTRIES.items():
        for country in countries:
            result[continent][alpha_map[MAPPINGS.get(country, country)]] = {
                "name": country
            }
    result = {k: _order_countries_dict(v) for k, v in result.items()}
    result = OrderedDict(sorted(result.items(), key=lambda t: t[0]))
    return result


# for a,b in get_countries_dict().items():
#     for x,y in b.items():
#         print(a,x,y)
